from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
LOG_DIR = PROJECT_ROOT / "logs"
LOG_PATH = LOG_DIR / "fetch.logs"
DATA_PATH = PROJECT_ROOT / "data"
TEMP_PATH = DATA_PATH / "temp"
JSON_PATH = PROJECT_ROOT / "data" / "temp" / "articles.json"

TEMP_PATH.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

REQUEST_TIMEOUT_LIMIT = 30

# API Configuration
BASE_URL = "https://api.gdeltproject.org/api/v2/doc/doc"

THEMES = [
    "ECON_STOCKMARKET",
    "ECON_CENTRALBANK",
    "ECON_INTEREST_RATES",
    # "ECON_INFLATION",
    # "ECON_WORLDCURRENCIES",
    # "ECON_CURRENCY_EXCHANGE_RATE",
    "EPU_ECONOMY",
    # "EPU_POLICY",
    "EPU_CATS_FINANCIAL_REGULATION",
    # "EPU_CATS_MONETARY_POLICY",
    "ECON_TAXATION",
    "ECON_IPO",
]


FINANCIAL_KEYWORDS = {
    # Market Performance
    "stock",
    "stocks",
    "share",
    "shares",
    "equity",
    "equities",
    "market",
    "markets",
    "trading",
    "trader",
    "traders",
    "nasdaq",
    "dow jones",
    "s&p 500",
    "ftse",
    "index",
    "indices",
    "rally",
    "rallied",
    "surge",
    "surged",
    "plunge",
    "plunged",
    "soar",
    "soared",
    "tumble",
    "tumbled",
    "volatility",
    "volatile",
    # Financial Metrics
    "revenue",
    "revenues",
    "profit",
    "profits",
    "earnings",
    "income",
    "loss",
    "losses",
    "margin",
    "margins",
    "ebitda",
    "eps",
    "p/e ratio",
    "valuation",
    "valued",
    "market cap",
    "market capitalization",
    "dividend",
    "dividends",
    "yield",
    "quarterly",
    "annual",
    "fiscal",
    "guidance",
    "forecast",
    "outlook",
    # Financial Reporting
    "earnings report",
    "quarterly report",
    "annual report",
    "financial results",
    "financial statement",
    "balance sheet",
    "cash flow",
    "sec filing",
    "10-k",
    "10-q",
    "beat expectations",
    "missed expectations",
    "earnings call",
    "conference call",
    # Investment & Trading
    "investment",
    "investments",
    "investor",
    "investors",
    "investing",
    "portfolio",
    "asset",
    "assets",
    "fund",
    "funds",
    "hedge fund",
    "mutual fund",
    "etf",
    "ipo",
    "initial public offering",
    "listing",
    "delisting",
    "buy",
    "sell",
    "hold",
    "rating",
    "upgrade",
    "downgrade",
    "price target",
    "bull",
    "bullish",
    "bear",
    "bearish",
    "uptick",
    "downtick",
    # Corporate Finance
    "acquisition",
    "merger",
    "m&a",
    "takeover",
    "buyout",
    "deal",
    "financing",
    "debt",
    "loan",
    "bond",
    "bonds",
    "credit",
    "leverage",
    "refinancing",
    "restructuring",
    "bankruptcy",
    "liquidation",
    "capital",
    "funding",
    "raise",
    "raised",
    "offering",
    "dilution",
    # Company Performance
    "growth",
    "decline",
    "expansion",
    "contraction",
    "performance",
    "sales",
    "demand",
    "supply",
    "competition",
    "competitive",
    "market share",
    "strategy",
    "strategic",
    "initiative",
    # Financial Health
    "profitable",
    "unprofitable",
    "solvent",
    "insolvent",
    "liquidity",
    "solvency",
    "default",
    "writedown",
    "impairment",
    "reserves",
    # Analyst & Investor Relations
    "analyst",
    "analysts",
    "research",
    "wall street",
    "institutional",
    "shareholder",
    "shareholders",
    "stakeholder",
    "stakeholders",
    "institutional investor",
    "retail investor",
    "insider trading",
    # Regulation & Compliance
    "sec",
    "securities",
    "regulation",
    "regulatory",
    "compliance",
    "audit",
    "auditor",
    "investigation",
    "lawsuit",
    "settlement",
    # Economic Indicators
    "inflation",
    "deflation",
    "interest rate",
    "fed",
    "federal reserve",
    "central bank",
    "monetary policy",
    "fiscal policy",
    "gdp",
    "recession",
    "economy",
    "economic",
    "macro",
    "microeconomic",
    # Valuation Terms
    "overvalued",
    "undervalued",
    "fair value",
    "intrinsic value",
    "book value",
    "enterprise value",
    "multiple",
    "multiples",
    # Financial Actions
    "dividend payout",
    "stock split",
    "reverse split",
    "buyback",
    "share repurchase",
    "capital expenditure",
    "capex",
    "opex",
    "cost cutting",
    "layoff",
    "layoffs",
    "restructuring cost",
}
